MD013: false

# Require ATX-style headings (# instead of = or -)
MD003:
  style: atx

# Enforce consistent list indentation
MD007:
  indent: 2

# Allow multiple consecutive blank lines for flexibility
MD012: false

# Enforce trailing punctuation in headings for consistency
MD026:
  punctuation: ".,;:!?"

# Allow inline HTML for flexibility in Markdown rendering
MD033: false

# Disable first-line heading requirement to allow flexibility in document structure
MD041: false

# Enforce consistent quote style
MD014:
  style: double

# Disable no-space-in-emphasis to allow flexibility in emphasis formatting
MD036: false

# Enforce proper list marker style (e.g., - or *)
MD032:
  style: dash
