---
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: 'chore: [pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: quarterly
    skip: []
    submodules: false

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: check-json
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace
          - id: fix-byte-order-marker

    - repo: https://github.com/crate-ci/typos
      rev: v1.48.0
      hooks:
          - id: typos
            args: []
            files: \.(md|html)$

    - repo: https://github.com/rbubley/mirrors-prettier
      rev: v3.9.4
      hooks:
          - id: prettier

    - repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: v0.22.1
      hooks:
          - id: markdownlint-cli2
            args:
                - --config
                - .markdownlint.yaml

    - repo: https://github.com/thibaudcolas/pre-commit-stylelint
      rev: v16.26.1
      hooks:
          - id: stylelint
            args: [--fix]
            files: \.(css|scss|sass)$
            additional_dependencies:
                - stylelint@16.9.0
                - stylelint-config-standard@36.0.1

    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.11.26
      hooks:
          # Update the uv lockfile
          - id: uv-lock

    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.30.1
      hooks:
          - id: gitleaks
